
package webServiceResources;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-20T15:22:44.194+01:00
 * Generated source version: 3.2.7
 *
 */
public final class MessageService_MessageServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webService/", "MessageServiceImplService");

    private MessageService_MessageServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MessageServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MessageServiceImplService ss = new MessageServiceImplService(wsdlURL, SERVICE_NAME);
        MessageService port = ss.getMessageServiceImplPort();

        {
        System.out.println("Invoking removeAllMessages...");
        java.lang.String _removeAllMessages__return = port.removeAllMessages();
        System.out.println("removeAllMessages.result=" + _removeAllMessages__return);


        }
        {
        System.out.println("Invoking getAllMessages...");
        java.util.List<webServiceResources.Message> _getAllMessages__return = port.getAllMessages();
        System.out.println("getAllMessages.result=" + _getAllMessages__return);


        }
        {
        System.out.println("Invoking removeMessage...");
        long _removeMessage_arg0 = 0;
        webServiceResources.Message _removeMessage__return = port.removeMessage(_removeMessage_arg0);
        System.out.println("removeMessage.result=" + _removeMessage__return);


        }
        {
        System.out.println("Invoking addMessage...");
        webServiceResources.Message _addMessage_arg0 = null;
        webServiceResources.Message _addMessage__return = port.addMessage(_addMessage_arg0);
        System.out.println("addMessage.result=" + _addMessage__return);


        }
        {
        System.out.println("Invoking updateMessage...");
        webServiceResources.Message _updateMessage_arg0 = null;
        webServiceResources.Message _updateMessage__return = port.updateMessage(_updateMessage_arg0);
        System.out.println("updateMessage.result=" + _updateMessage__return);


        }
        {
        System.out.println("Invoking getMessage...");
        long _getMessage_arg0 = 0;
        webServiceResources.Message _getMessage__return = port.getMessage(_getMessage_arg0);
        System.out.println("getMessage.result=" + _getMessage__return);


        }

        System.exit(0);
    }

}
