package webServiceResources;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-20T15:22:44.230+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://webService/", name = "MessageService")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageService {

    @WebMethod
    @RequestWrapper(localName = "removeAllMessages", targetNamespace = "http://webService/", className = "webServiceResources.RemoveAllMessages")
    @ResponseWrapper(localName = "removeAllMessagesResponse", targetNamespace = "http://webService/", className = "webServiceResources.RemoveAllMessagesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String removeAllMessages();

    @WebMethod
    @RequestWrapper(localName = "getAllMessages", targetNamespace = "http://webService/", className = "webServiceResources.GetAllMessages")
    @ResponseWrapper(localName = "getAllMessagesResponse", targetNamespace = "http://webService/", className = "webServiceResources.GetAllMessagesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<webServiceResources.Message> getAllMessages();

    @WebMethod
    @RequestWrapper(localName = "removeMessage", targetNamespace = "http://webService/", className = "webServiceResources.RemoveMessage")
    @ResponseWrapper(localName = "removeMessageResponse", targetNamespace = "http://webService/", className = "webServiceResources.RemoveMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public webServiceResources.Message removeMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addMessage", targetNamespace = "http://webService/", className = "webServiceResources.AddMessage")
    @ResponseWrapper(localName = "addMessageResponse", targetNamespace = "http://webService/", className = "webServiceResources.AddMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public webServiceResources.Message addMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        webServiceResources.Message arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateMessage", targetNamespace = "http://webService/", className = "webServiceResources.UpdateMessage")
    @ResponseWrapper(localName = "updateMessageResponse", targetNamespace = "http://webService/", className = "webServiceResources.UpdateMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public webServiceResources.Message updateMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        webServiceResources.Message arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://webService/", className = "webServiceResources.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://webService/", className = "webServiceResources.GetMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public webServiceResources.Message getMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );
}
