package webServiceResources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-14T20:57:58.420+01:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "MessageServiceImplService",
                  wsdlLocation = "file:/D:/Praca i nauka/Projekty/Intellij Ultimate/MGR/SoapMessageClient/src/webServiceResources/MessageService.wsdl",
                  targetNamespace = "http://webService/")
public class MessageServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService/", "MessageServiceImplService");
    public final static QName MessageServiceImplPort = new QName("http://webService/", "MessageServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Praca i nauka/Projekty/Intellij Ultimate/MGR/SoapMessageClient/src/webServiceResources/MessageService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MessageServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Praca i nauka/Projekty/Intellij Ultimate/MGR/SoapMessageClient/src/webServiceResources/MessageService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MessageServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MessageServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MessageServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MessageServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MessageServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MessageService
     */
    @WebEndpoint(name = "MessageServiceImplPort")
    public MessageService getMessageServiceImplPort() {
        return super.getPort(MessageServiceImplPort, MessageService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageService
     */
    @WebEndpoint(name = "MessageServiceImplPort")
    public MessageService getMessageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MessageServiceImplPort, MessageService.class, features);
    }

}
